### ISSUE TITLE
Unlinked Mentions Backlinks do not show up.

### ISSUE THREAD

**Issue by Robinaite** [kdnk/obsidian-hierarchy#1]
Unlinked Mentions Backlinks do not show up. The plugin only works for Linked mentions. Obsidian V1.7.7 on Windows.

![Obsidian_20-21-29-12](https://github.com/user-attachments/assets/acdbb4b0-dcd0-450e-a4ff-45dcf511fff8)

If it's not too complicated I would love to have it work for Unlinked Mentions as well! This makes my life so much easier when I have multiple of the same names in different folders. Already been massively helpful in the linked mentions section!

**Comment by kdnk** [comment]
@Robinaite I implemented it in 0.3.1, so please give it a try.
Due to the lack of capabilities of Obsidian's API, this is a heuristic implementation.
Let me know if you find there are something wrong.
